# Generated by Django 5.2.10 on 2026-02-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy_middleware', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legacyapitoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
