# Generated by Django 5.2.10 on 2026-02-25 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_image_options_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterField(
            model_name='image',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='blog/images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='image',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(db_default='Ella Skin & Spa Wellness Team', max_length=255, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='banner_image_url',
            field=models.CharField(blank=True, help_text='Banner image URL', max_length=255, null=True, verbose_name='Banner URL'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='keywords',
            field=models.CharField(help_text='Separated by commas', max_length=255, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='post',
            name='lang',
            field=models.CharField(choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=2, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='post',
            name='related_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.post', verbose_name='Related post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
